/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppRoot {}
  interface FormAddContact {
    'fetchAddItem': { AddItem: Function };
  }
  interface ListContact {
    'contacts': {
      name: string;
      number: string;
      readonly id: string;
    }[];
    'fetchDeleteItem': { deleteItem: Function };
  }
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLFormAddContactElement extends Components.FormAddContact, HTMLStencilElement {}
  var HTMLFormAddContactElement: {
    prototype: HTMLFormAddContactElement;
    new (): HTMLFormAddContactElement;
  };

  interface HTMLListContactElement extends Components.ListContact, HTMLStencilElement {}
  var HTMLListContactElement: {
    prototype: HTMLListContactElement;
    new (): HTMLListContactElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'form-add-contact': HTMLFormAddContactElement;
    'list-contact': HTMLListContactElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot {}
  interface FormAddContact {
    'fetchAddItem'?: { AddItem: Function };
  }
  interface ListContact {
    'contacts'?: {
      name: string;
      number: string;
      readonly id: string;
    }[];
    'fetchDeleteItem'?: { deleteItem: Function };
  }

  interface IntrinsicElements {
    'app-root': AppRoot;
    'form-add-contact': FormAddContact;
    'list-contact': ListContact;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'form-add-contact': LocalJSX.FormAddContact & JSXBase.HTMLAttributes<HTMLFormAddContactElement>;
      'list-contact': LocalJSX.ListContact & JSXBase.HTMLAttributes<HTMLListContactElement>;
    }
  }
}


